# Generated by Django 5.1.1 on 2024-10-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttour',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commenttour',
            name='tour',
        ),
        migrations.DeleteModel(
            name='CommentLocation',
        ),
        migrations.DeleteModel(
            name='CommentTour',
        ),
    ]
